### ISSUE TITLE
Counting Tokens

### ISSUE THREAD

**Issue by Matthaeus07** [knuddelsgmbh/jtokkit#4]
May I ask if it is possible to count the tokens a given text has using this library?

Let's say I want to count how many tokens "Hello World" has. How would I do that?

Thank you in advance!

**Comment by Plexcalibur** [comment]
> May I ask if it is possible to count the tokens a given text has using this library?
> 
> Let's say I want to count how many tokens "Hello World" has. How would I do that?
> 
> Thank you in advance!

This should do the trick:
`EncodingRegistry registry = Encodings.newDefaultEncodingRegistry();
Encoding enc = registry.getEncoding(EncodingType.CL100K_BASE);
int tokens = enc.encode("Hello World").size();`

**Comment by tox-p** [comment]
Since this usecase is so common and was the main driver to build this library, there even is a shorthand:

```
EncodingRegistry registry = Encodings.newDefaultEncodingRegistry();
Encoding enc = registry.getEncoding(EncodingType.CL100K_BASE);
int tokens = enc.countTokens("Hello World");
```

But internally, it also just does `encode(...).size();`

Also, take a look at the JavaDoc of the Encoding Interface. I updated it with usage examples:

https://javadoc.io/static/com.knuddels/jtokkit/0.2.0/com/knuddels/jtokkit/api/Encoding.html

**Comment by Matthaeus07** [comment]
This is great! I love this library!

You should definitely add this as an example to the main `readme.md` tho.

**Comment by tox-p** [comment]
Yes, more extensive documentation + some kind of recipes section is on my todo list 😄
