### ISSUE TITLE
can you include the mvn bnd plugin to generate a osgi/bundle correct manifest?

### ISSUE THREAD

**Issue by jcompagner** [knuddelsgmbh/jtokkit#63]
see: 
https://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html

should be only a few lines in the pom 

This way its a better bundle with all the info you want to have there, and it can be consumed better by tools that really use this.

**Comment by tox-p** [comment]
The last time I worked with OSGI or Maven is more than a decade ago 😄 but this sounds interesting, I will take a look 👍

**Comment by tox-p** [comment]
I am currently unable to invest time into this issue. Feel free to tackle it yourself (or anyone reading this, who also wants this functionality), but keep in mind, that JTokkit uses Gradle instead of Maven and therefore your proposed plugin is not compatible (but there are Gradle equivalents, which may lead to your desired result)

**Comment by Plexcalibur** [comment]
closed due to inactivity
